name: Check Formatting
on: [pull_request, push]
jobs:
  ec-audit-pr:
    runs-on: ubuntu-20.04
    name: Validate EditorConfig
    steps:
      - uses: actions/checkout@v3
      - name: Set up editorconfig-checker
        uses: editorconfig-checker/action-editorconfig-checker@main
      - name: Run editorconfig-checker
        run: editorconfig-checker
  validate-json:
    runs-on: ubuntu-latest
    name: Validate JSON
    steps:
      - uses: actions/checkout@v3
      - name: Run ajv
        uses: docker://orrosenblatt/validate-json-action:latest
        env:
          INPUT_SCHEMA: /schema.json
          INPUT_JSONS: /manifest.json
