name: Check Formatting
on: [pull_request]
jobs:
  ec-audit-pr:
    steps:
      - name: EditorConfig Audit PR
        uses: zbeekman/EditorConfig-Action@v1.1.0
  validate-json:
    steps:
      - uses: actions/checkout@v1
      - name: Validate JSON
        uses: docker://orrosenblatt/validate-json-action:latest
        env:
          INPUT_SCHEMA: /schema.json
          INPUT_JSONS: /manifest.json
