name: Generate mods list markdown

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  Generate-Markdown:
    if: github.repository == 'neos-modding-group/neos-mod-manifest'
    runs-on: ubuntu-latest
    steps:
      - name: checkout master
        uses: actions/checkout@v3

      - name: checkout gh-pages
        uses: actions/checkout@v3
        with:
          repository: neos-modding-group/neos-modding-group.github.io
          path: gh-pages
          ssh-key: ${{ secrets.PAGES_AUTH }}

      - name: setup python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
          cache: "pip"

      - name: generate readme
        run: |
          cp gh-pages/.templates/mod-list-template.md gh-pages/mods.md
          pip3 install -r requirements.txt
          python3 gen_readme.py < manifest.json >> gh-pages/mods.md

      - name: commit
        env:
          PAGES_AUTH: ${{ secrets.PAGES_AUTH }}
        run: |
          cd gh-pages
          git diff --quiet --exit-code mods.md && exit 0
          mkdir -p "~/.ssh"
          echo "$PAGES_AUTH" > "~/.ssh/id_rsa"
          git config user.name "GitHub Actions"
          git config user.email "<>"
          git add --force mods.md
          git commit -m "Update mod list"
          git push origin master
